### ISSUE TITLE
基本没法用

### ISSUE THREAD

**Issue by iwvw** [k0baya/QLonRAILWAY#1]
没有外部数据库，一重启就重置了

**Comment by k0baya** [comment]
> 没有外部数据库，一重启就重置了

render就是这样。你要用render还要保留数据的话，需要你自行把数据单独存在文件夹内，然后编辑dockerfile，添加把数据文件夹复制进去的命令。railway没有这个问题。想折腾render的话你可以自行修改修改试试。欢迎修改之后提交PR添加新的分支。
