### ISSUE TITLE
data的数据怎么上传？

### ISSUE THREAD

**Issue by 2201865585** [k0baya/QLonRAILWAY#2]
难道是先再本地部署，设置好后，将本地数据上传？

**Comment by k0baya** [comment]
目前似乎由于render的封锁无法正常部署。由于滥用行为我的render账号已被封禁，解封之前暂时无法测试寻找解决办法。可以另寻其他平台进行尝试，例如koyeb什么的。

**Comment by 2201865585** [comment]
我昨晚部署的暂时可以用，建议研究下replit是否能部署

**Comment by k0baya** [comment]
> 我昨晚部署的暂时可以用，建议研究下replit是否能部署

Replit无法部署Docker，而小雅镜像内的各种脚本经过了混淆加密，想手动部署到Replit难度很大。

**Comment by k0baya** [comment]
> 我昨晚部署的暂时可以用，建议研究下replit是否能部署

的确可以部署到Replit，但是无法正常使用。由于青龙的硬盘空间需求比较大，Replit部署完就没有空间装依赖了。

**Comment by 2201865585** [comment]
之前用大象数据库作为外联数据库，把alist部署再render上，但不知道部署青龙时变量都怎么写
