### ISSUE TITLE
大佬，CodeSandBox部署青龙的方法呢？

### ISSUE THREAD

**Issue by humoumu** [k0baya/QLonRAILWAY#4]

**Comment by sfdafaa** [comment]
劝你放弃。CodeSandBox很离谱的，青龙完全没法跑。我弄了两个一秒加一死循环测试一下，五分钟的死循环运行了了十几分钟，七分钟的二十多分钟。而且最关键的是青龙有时候会卡的不执行任务，有的时候，拼命添加之前应该执行但是没有执行的任务。我第一次试一分钟执行一次的死循环，卡了200+待执行。
你想试试可以去这里https://codesandbox.io/search?query=qinglong。

**Comment by k0baya** [comment]
> 劝你放弃。CodeSandBox很离谱的，青龙完全没法跑。我弄了两个一秒加一死循环测试一下，五分钟的死循环运行了了十几分钟，七分钟的二十多分钟。而且最关键的是青龙有时候会卡的不执行任务，有的时候，拼命添加之前应该执行但是没有执行的任务。我第一次试一分钟执行一次的死循环，卡了200+待执行。 你想试试可以去这里[https://codesandbox.io/search?query=qinglong。](https://codesandbox.io/search?query=qinglong%E3%80%82)

你需要在其他地方（比如你的软路由或者服务器）用playwright或者selenium，使用你的csb的cookies对csb的编辑器进行监控。不过目前CodeSandBox政策已经改变，DevBox的免费时长似乎不能整月覆盖了 ，没什么意义了。

**Comment by immortaker** [comment]
> > 劝你放弃。 CodeSandBox很离谱的，青龙完全没法跑。 我弄了两个一秒加一死循环测试一下，五分钟的死循环运行了了十几分钟，七分钟的二十多分钟。 而且最关键的是青龙有时候会卡的不执行任务，有的时候，拼命添加之前应该执行但是没有执行的任务。 我第一次试一分钟执行一次的死循环，卡了200+待执行。 你想试试可以去这里[https://codesandbox.io/search?query=qinglong。 ](https://codesandbox.io/search?query=qinglong%E3%80%82)
> 
> 你需要在其他地方（比如你的软路由或者服务器）用playwright或者selenium，使用你的csb的cookies对csb的编辑器进行监控。 不过目前CodeSandBox政策已经改变，DevBox的免费时长似乎不能整月覆盖了 ，没什么意义了。
那大佬还有推荐的平台挂青龙吗
